### ISSUE TITLE
executable jar not created

### ISSUE THREAD

**Issue by reddyvasavi** [manuel-freire/ac2#1]

**Comment by reddyvasavi** [comment]
ac-ui/target/ac-version-githash.jar is not created

**Comment by manuel-freire** [comment]
Please add exact steps to reproduce, including your java and maven versions (from `java -version` and `mvn -version`, respectively), and the command you use to create the executable. In my case, with the latest source, java openjdk 1.8.0_151, and maven 3.3.1, and after entering the command `mvn package`:

      [...] assembly file: ac2/ac-ui/target/ac-2.1.2-SNAPSHOT-acf64.jar
      [...]
      BUILD SUCCESS

Also recall that you can use the [latest compiled version](https://github.com/manuel-freire/ac2/releases/latest) instead of building it from source.

**Comment by manuel-freire** [comment]
Closing issue, since it cannot be reproduced.
