### ISSUE TITLE
comparison without graphical interface

### ISSUE THREAD

**Issue by shreykshah** [manuel-freire/ac2#29]
Is it possible to run this via command line without the graphical interface?

**Comment by manuel-freire** [comment]
It is possible - see [CommandLineMain](https://github.com/manuel-freire/ac2/blob/master/ac-ui/src/main/java/es/ucm/fdi/ac/CommandLineMain.java)

You can call it like this
`java -cp <latest-release-jar> es.ucm.fdi.ac.CommandLineMain -h`
to see the help file. Note that, unlike the graphical version, you must have prepared submissions so that each folder that you pass to **CommandLineMain** corresponds to 1 submission, with only the files of that submission that you wish to compare. Output should be a CSV table with distances from each submission to all others (therefore, O(N^2))
